//
// Created by Franck GUTMANN on 15/02/2023.
//

#ifndef PACMAN_CONSTANTS_H
#define PACMAN_CONSTANTS_H

#define GAME_TITLE "PacMan"

#define GAME_START_DURATION 700
#define READY_DURATION 300

#define CELL_SIZE 25
#define MAP_WIDTH 21
#define MAP_HEIGHT 27

#define MAZE_SCREEN_HEIGHT 675
#define HEADER_SCREEN_HEIGHT 75
#define FOOTER_SCREEN_HEIGHT 40
#define TOTAL_SCREEN_WIDTH 525
#define TOTAL_SCREEN_HEIGHT (MAZE_SCREEN_HEIGHT + HEADER_SCREEN_HEIGHT + FOOTER_SCREEN_HEIGHT)

#define TUNNEL_POSITION_Y 13
#define TUNNEL_LENGTH 5

#define PATH_FILE_MAZE "../assets/text/maze.txt"
#define PATH_SPRITE_SHEET_PACMAN "../assets/img/pacman_sprites.bmp"
#define PATH_LOGO_LIVL_PACMAN "../assets/img/logo_livl_pacman.bmp"

#define GAME_SPEED 260
#define ANIMATION_SPEED 14 // BIGGER IS SLOWER

#define GHOST_INITIAL_POS_X 4
#define GHOST_INITIAL_POS_Y 124
#define GHOST_SPACING_X 3
#define GHOST_SPACING_Y 4
#define GHOST_SIZE 14
#define GHOST_COUNT 4

#define PACMAN_SIZE 14
#define PACMAN_SPRITE_MOUTHS_DIRECTION 3
#define PACMAN_SPACING_X 3
#define PACMAN_SPACING_Y 2

#define PACMAN_DEATH_ANIMATION_FRAMES 10
#define PACMAN_DEATH_ANIMATION_DURATION 200
#define PACMAN_DEATH_ANIMATION_DELAY 100
#define GAME_OVER_DURATION 500

#define EATABLE_GHOST_DURATION 1000

#define SCORE_GHOST_EATEN_DURATION 150 // when pacman eat a ghost
#define SCORE_GHOST_MAX_COMBO 4

#define INITIAL_LIVES 3

#define BIG_COIN_RATE 50 < 30
#define TEXT_UP_RATE 125 < 75

#define FRUIT_SPAWN_1 70
#define FRUIT_SPAWN_2 170
#define FRUIT_APPEAR_DURATION 2000
#define FRUIT_SCORE_DISPLAY_DURATION 150

#define NEXT_ROUND_ANIMATION_DURATION 500
#define MAZE_BLINK_WHITE_BLUE_RATE 50 < 25

#define DEFAULT_SPEED 1
#define DEFAULT_POSITION_DISTANCE 1

#endif // PACMAN_CONSTANTS_H
