name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install dependencies
      run: sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev -y
    
    - name: Build project
      run: make
